import Home from './Home'
import Template from './Template'
import Products from './Products'
import Agents from './Agents'
import Expenses from './Expenses'
import Forms from './Forms'
import Orders from './Orders'
import OutgoingStock from './OutgoingStock'
import PaymentGateways from './PaymentGateways'
import SmsTemplating from './SmsTemplating'
import StockLeft from './StockLeft'
import Report from './Report'
import StoreSettings from './StoreSettings'
import Users from './Users'

export { Home, Template, Products, Agents, Expenses, Forms, Orders, OutgoingStock, PaymentGateways, Report, SmsTemplating, StockLeft, StoreSettings, Users }